name: test

# As recommended by Graphite
# (https://graphite.dev/docs/github-configuration-guidelines#github-actions)
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

# Cancel in-progress jobs for the same work
# (https://graphite.dev/docs/troubleshooting#why-are-my-actions-running-twice)
concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}-${{ github.ref == 'refs/heads/main' && github.sha || ''}}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install devbox
        uses: jetpack-io/devbox-install-action@v0.11.0
        with:
          enable-cache: true
          devbox-version: 0.13.6

      - name: Install dependencies
        run: devbox run pnpm install

      # - name: Dump Playwright Information
      #   run: |
      #     echo -------------------------------------------------------
      #     devbox shellenv | grep PLAYWRIGHT
      #     echo -------------------------------------------------------
      #     echo "playwright version:"
      #     devbox run playwright --version
      #     echo -------------------------------------------------------
      #     echo "@playwright/test version:"
      #     devbox run pnpm ls -r @playwright/test
      #     echo -------------------------------------------------------

      - name: Validate and Build
        run: |
          devbox run pnpm prep

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: "**/playwright-report/"
          retention-days: 30
